---
title: "DAX Notes"
format: 
  html:
    toc: true 
    toc-depth: 5
    toc-location: right
    code-tools: true  
    code-copy: true
    code-fold: false
    self-contained: true
    anchor-sections: false
    theme: cerulean
---




:::::::::::::: {.columns}
::: {.column width="50%"}

### Calculated Columns

Calculated columns are columns (similar to dplyr's `mutate()`).

- Used for evaluating each row
- Adds a new column to an existing table
- Calculated at data load and when the data is refreshed
- Returns one value per row
- Stored in memory; pre-calculated and appended to each row in a table and stored inside the data model
- Evaluated at row level
- Profit = Revenue - Cost is an example of a calculated column 

:::
::: {.column width="50%"}

### Calculated Measures

Measures are single numbers (like dplyr's `summary()`)

- For aggregating multiple rows
- Results in a nother field that you can add to a visualization
- Calculated at query time as you interact and filter
- Not stored in memory; makes use of CPU and is recalculated each time a filter/slicer changes
- Evaluated based on the set of data selected i.e. filters and slicers being applied in the report.
- SUM(Sales) is an example of a calculated measure

:::
::::::::::::::



## Measures

- use `VAR` to declare variables
- CTRL + / to make a comment //


#### CALCULATE()

- The arguments to `CALCULATE()` are tables