---
title: "Data Science Learned from BYU-I"
author: "Brigham Eaquinto"
date: "July 2022"
format: 
  html:
    toc: true 
    toc-depth: 5
    toc-location: right
    code-tools: true  
    code-copy: true
    code-fold: false
    self-contained: true
    anchor-sections: false
    theme: cerulean
---


### Tools Learned 

----

:::::::::::::: {.columns}
::: {.column width="50%"}

- Coding Languages
    - R 
    - Python
    - SQL 
    - DAX

:::
::: {.column width="50%"}

- IDEs 
    - VSCode
    - RStudio
    - DataBricks

:::
::::::::::::::

:::::::::::::: {.columns}
::: {.column width="50%"}

- R Packages
    - Tidyverse (Dplyr, Ggplot2)
    - [stats](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/00Index.html) ([Saunder's Notebook](https://byuistats.github.io/Statistics-Notebook/))
    - OfficeR

:::
::: {.column width="50%"}

- Python Packages
    - [Pyspark & Spark SQL](python_packages\spark\pyspark_notes.html)
    - [Tensorflow & Keras](python_packages\tensorflow_keras_notes.html) 
    - [Sklearn](python_packages\sklearn_notes.html) 
    - [Pandas](python_packages\pandas_notes.html)
    - [Numpy](python_packages\numpy_notes.html)
    - [Seaborn](python_packages\seaborn_notes.html)
    - [Plotnine](python_packages\plotnine_notes.html)
    - [Spacy](python_packages\spacy_notes.html)
    - [Gensim](python_packages\gensim_notes.html) 

:::
::::::::::::::



- Reporting Tools: 
    - [QMD](qmd/qmd_notes.html)
    - Streamlit Dashboard 
    - Power BI Reports
 

- __Others__
    - IDAS 
    - Pathway Internship 
    - DSS

 
# Curriculum


### Noteable Data Science Classes
- CIT 111 Introduction to Databases
- CIT 225 Database Design & Development
- DS 250 Data Science Programming 
- DS 350 Data Wrangling and Visualization
- DS 460 Big Data Programming & Analytics
- DS 498R Internship
- DS 499 Senior Project in Data Science 
- MATH 325 Intermediate Statistics 
- MATH 425 Applied Linear Regression
- MATH 488 Statistical and Data Science Consulting
- CSE 450 Machine Learning 
- BA 315 Business Analytics



### Notable Math Classes
- MATH 112X Calculus 1
- MATH 215 Multivariable Calculus 
- MATH 316 Differential Equations and Linear Algebra
- MATH 341 Linear Algebra 
- MATH 423 Probability and Statistics 