---
title: "DAX Notes"
format: 
  html:
    toc: true 
    toc-depth: 5
    toc-location: right
    code-tools: true  
    code-copy: true
    code-fold: false
    self-contained: true
    anchor-sections: false
    theme: cerulean
---




:::::::::::::: {.columns}
::: {.column width="50%"}

### Calculated Columns

Calculated columns are columns (similar to dplyr's `mutate()`).

- Used for evaluating each row
- Adds a new column to an existing table
- Calculated at data load and when the data is refreshed
- Returns one value per row
- Stored in memory; pre-calculated and appended to each row in a table and stored inside the data model
- Evaluated at row level
- Profit = Revenue - Cost is an example of a calculated column 

:::
::: {.column width="50%"}

### Calculated Measures

Measures are single numbers (like dplyr's `summary()`)

- For aggregating multiple rows
- Results in a nother field that you can add to a visualization
- Calculated at query time as you interact and filter
- Not stored in memory; makes use of CPU and is recalculated each time a filter/slicer changes
- Evaluated based on the set of data selected i.e. filters and slicers being applied in the report.
- SUM(Sales) is an example of a calculated measure

:::
::::::::::::::



## Measures

- use `VAR` to declare variables
- CTRL + / to make a comment //


#### CALCULATE()

- The arguments to `CALCULATE()` are tables




# DataCamp Course: Introduction to DAX in Power BI

## Chapter 1: Getting Started with DAX


## Chapter 2: Context in DAX Formulas

What is this concept of 'context in DAX formulas'??
- three types of context: row, filter, and query

### Row Context:
- I think row context is the same effect as a calculated column because it iterates through each row
  - this makes me wonder if the iterator functions should replace calculated columns all together
- You can tell they're iterator functions if there is an x at the end of the function name like `SUMX()`

### Filter Context: 
- Filter context is a set of filters that have been applied before the calculation is carried out

#### The Calculate Function: 
- the first argument is a measure or calculation to be evaluated. After that argument, optional filters are allowed.

### Query Context: 
The query context is not covered in this course

### Making Variables in DAX
To make variables 

Here's an example of using variables in a DAX measure

```{python}
#| eval: false

Gold21vs20 = 
VAR GoldVolume20 = CALCULATE (
  SUM ( Commodities[Volume] ), 
  FILTER ( Commodities, Commodities[Symbol] = "Gold" ), 
  Filter ( Commodities, YEAR ( Commodities[Date] ) = 2020 )
)
RETURN DIVIDE([GoldVolume21] - GoldVolume20, GoldVolume20)
```






Tennyson Notes:
- based on lots of learning at home (politics, history, econ)
- 6 bigs institutions that control culture ( ed, tech, hollywood, govt, military, ...)
- spreading communism through the world. Not from top down, culture would transform govenment. Politics are down stream of culture
- Start in ed for youth and holywood
- People like stories rather than facts
- high school started in 1920 and for only 4 months of the year
- Not age based grades: 8 levels. Dependent on mastery of the level. Genreally on level per year
- what about not mon-fri school so that there is more for family time? Three days a week?
- wall builders
- Case study on the 9-6 schools? Sleep there and everythign

- Knowing all of this, I need to start a school.
- Tool parents too. 
- NAtalie Cline state board of education
- 80 emails. BYU woke administration. 
- Liahona and American Heritage
- Is this your fulltime gig right now? 
- Topics: 
  - funding
  - location
  - ciriculum: 
    - 
- texas school with Glen Beck's wife
get funding from rich conservatives in Mapleton
- I want to make my own textbooks to be vertically integrated. 
- "I want you to be just as invested in your children's education as you are in your full time job."
- 