project:
  type: website
  output-dir: _output
  preview:
    port: 3141

website:
  title: "BYUIDS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    title: "Title here"
    style: "docked"
    search: true
    alignment: right
    collapse-level: 1
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd

format:
  html:
    theme:
      light: [cerulean, style/dsbox.scss]
      dark: [cerulean, style/dsbox.scss, style/dark.scss]
    css: styles.css
    toc: true



