---
title: "PySpark vs Spark SQL"
format: 
  html:
    toc: false
    code-tools: true  
    code-copy: true
    code-fold: false
    self-contained: true
    anchor-sections: false
    theme: cerulean
---

Or maybe, pyspark.sql vs. spark.sql?

What are the difference between these two? 

[Official Comprehensive Documentation](https://spark.apache.org/docs/latest/)
[Official PySpark Documentation](https://spark.apache.org/docs/latest/api/python/)
[Interesting DataBricks Documentation Link](https://databricks.com/databricks-documentation)


<!-- Here starts the section of the comparisons of the two in column format -->


:::::::::::::: {.columns}
::: {.column width="50%"}

<p align="center">__PySpark__</p>

PySpark has the SQL Functions module often imported as `F.function()`. It seems that is where most of the magic is with PySpark. 


:::
::: {.column width="50%"}

<p align="center">__Spark SQL__</p>


I believe that spark.sql is a SQL port into ANSI SQL. Spark SQL brings SQL to Spark, and this is brought to Python? 

This has all the things that SQL can do. PySpark has their own versions of SQL things. 

:::
::::::::::::::


<h4 align="center">Very Useful Links</h4>

:::::::::::::: {.columns}
::: {.column width="50%"}


- [PySpark Overview w/ API Reference at bottom](https://sparkbyexamples.com/pyspark-tutorial/)
- [PySpark Tutorials](https://sparkbyexamples.com/category/pyspark/)

:::
::: {.column width="50%"}



- [SparkbyExample SQL Functions](https://sparkbyexamples.com/spark/spark-sql-functions/)
- [Read the Docs-esk style from Apache.org SQL Functions](https://sparkbyexamples.com/spark/spark-sql-functions/)

:::
::::::::::::::



### Window Functions


The dplyr equivalent of a window function is a group_by() %>% mutate(). This keeps all the values where group_by() %>% summarize() does not. 

Partioning and grouping is similar, but different. Instead of gathering data into groups and then summarizing a value by groups and shorten this down into rows unique rows.

Would partioning work for making a rolling window?

The code to do it in PySpark is 

```{python}
#| eval: false

from pyspark.sql import Window
from pyspark.sql import functions as F

windowval = (Window.partitionBy('class').orderBy('time')
             .rowsBetween(Window.unboundedPreceding, 0))
df_w_cumsum = df.withColumn('cum_sum', F.sum('value').over(windowval))
df_w_cumsum.show()


```


### MLlib


Now, the Spark ML library only works with numeric data. But we still want to use the Sex and the Embarked column. For that, we will need to encode them. To do it let’s use something called the StringIndexer:


```{python}
#| eval: false

from pyspark.ml.feature import StringIndexer

dataset = StringIndexer(
    inputCol='Sex', 
    outputCol='Gender', 
    handleInvalid='keep').fit(dataset).transform(dataset)

dataset = StringIndexer(
    inputCol='Embarked', 
    outputCol='Boarded', 
    handleInvalid='keep').fit(dataset).transform(dataset)

dataset.show()
```
